from __future__ import annotations

import polars as pl
from interface_grafica.models.table_model import PolarsTableModel
from PySide6.QtWidgets import QTableView


class MainWindowProfilePresetsMixin:
    def _obter_colunas_preset_perfil(
        self, perfil: str, colunas: list[str], contexto: str
    ) -> list[str]:
        nome = (perfil or "").strip().lower()
        if contexto == "mov_estoque":
            mapa = {
                "padrao": [
                    "ordem_operacoes",
                    "Tipo_operacao",
                    "fonte",
                    "id_agrupado",
                    "descr_padrao",
                    "Descr_item",
                    "Descr_compl",
                    "Cod_item",
                    "Cod_barra",
                    "Ncm",
                    "Cest",
                    "Tipo_item",
                    "Chv_nfe",
                    "mod",
                    "Ser",
                    "num_nfe",
                    "Num_item",
                    "Dt_doc",
                    "Dt_e_s",
                    "nsu",
                    "finnfe",
                    "infprot_cstat",
                    "co_uf_emit",
                    "co_uf_dest",
                    "Cfop",
                    "Cst",
                    "Aliq_icms",
                    "Vl_bc_icms",
                    "Vl_icms",
                    "vl_bc_icms_st",
                    "vl_icms_st",
                    "aliq_st",
                    "Qtd",
                    "q_conv",
                    "Unid",
                    "unid_ref",
                    "fator",
                    "Vl_item",
                    "preco_item",
                    "preco_unit",
                    "custo_medio_anual",
                    "saldo_estoque_anual",
                    "entr_desac_anual",
                    "mov_rep",
                    "excluir_estoque",
                    "dev_simples",
                    "dev_venda",
                    "dev_compra",
                    "dev_ent_simples",
                    "ncm_padrao",
                    "cest_padrao",
                    "co_sefin_agr",
                    "it_pc_interna",
                    "it_in_st",
                    "it_pc_mva",
                    "it_in_mva_ajustado",
                    "it_in_isento_icms",
                    "it_in_reducao",
                    "it_pc_reducao",
                    "it_in_combustivel",
                    "it_in_pmpf",
                    "it_in_reducao_credito",
                ],
                "exportar": [
                    "ordem_operacoes",
                    "Tipo_operacao",
                    "fonte",
                    "id_agrupado",
                    "descr_padrao",
                    "Descr_item",
                    "Dt_doc",
                    "Dt_e_s",
                    "Cfop",
                    "Qtd",
                    "q_conv",
                    "saldo_estoque_anual",
                    "entr_desac_anual",
                    "custo_medio_anual",
                    "preco_item",
                    "preco_unit",
                    "unid_ref",
                    "fator",
                    "mov_rep",
                    "dev_simples",
                    "excluir_estoque",
                ],
                "contribuinte": [
                    "ordem_operacoes",
                    "Tipo_operacao",
                    "Dt_doc",
                    "id_agrupado",
                    "descr_padrao",
                    "Qtd",
                    "q_conv",
                    "unid_ref",
                    "preco_item",
                    "preco_unit",
                    "saldo_estoque_anual",
                    "entr_desac_anual",
                ],
                "auditoria": [
                    "ordem_operacoes",
                    "Tipo_operacao",
                    "fonte",
                    "id_agrupado",
                    "descr_padrao",
                    "Dt_doc",
                    "Dt_e_s",
                    "Cfop",
                    "q_conv",
                    "saldo_estoque_anual",
                    "entr_desac_anual",
                    "mov_rep",
                    "dev_simples",
                    "excluir_estoque",
                ],
                "auditoria fiscal": [
                    "ordem_operacoes",
                    "Tipo_operacao",
                    "fonte",
                    "id_agrupado",
                    "descr_padrao",
                    "Descr_item",
                    "Descr_compl",
                    "Cod_item",
                    "Cod_barra",
                    "Ncm",
                    "Cest",
                    "Tipo_item",
                    "Chv_nfe",
                    "mod",
                    "Ser",
                    "num_nfe",
                    "Num_item",
                    "Dt_doc",
                    "Dt_e_s",
                    "nsu",
                    "finnfe",
                    "infprot_cstat",
                    "co_uf_emit",
                    "co_uf_dest",
                    "Cfop",
                    "Cst",
                    "Aliq_icms",
                    "Vl_bc_icms",
                    "Vl_icms",
                    "vl_bc_icms_st",
                    "vl_icms_st",
                    "aliq_st",
                    "Qtd",
                    "q_conv",
                    "Unid",
                    "unid_ref",
                    "fator",
                    "Vl_item",
                    "preco_item",
                    "preco_unit",
                    "custo_medio_anual",
                    "saldo_estoque_anual",
                    "entr_desac_anual",
                    "mov_rep",
                    "excluir_estoque",
                    "dev_simples",
                    "dev_venda",
                    "dev_compra",
                    "dev_ent_simples",
                    "co_sefin_agr",
                    "it_pc_interna",
                    "it_in_st",
                    "it_pc_mva",
                    "it_in_mva_ajustado",
                    "it_in_isento_icms",
                    "it_in_reducao",
                    "it_pc_reducao",
                    "it_in_combustivel",
                    "it_in_pmpf",
                    "it_in_reducao_credito",
                ],
                "estoque": [
                    "ordem_operacoes",
                    "Tipo_operacao",
                    "id_agrupado",
                    "descr_padrao",
                    "Dt_doc",
                    "q_conv",
                    "saldo_estoque_anual",
                    "unid_ref",
                    "fator",
                ],
                "custos": [
                    "ordem_operacoes",
                    "Tipo_operacao",
                    "id_agrupado",
                    "descr_padrao",
                    "Dt_doc",
                    "q_conv",
                    "preco_item",
                    "preco_unit",
                    "custo_medio_anual",
                    "saldo_estoque_anual",
                ],
            }
        elif contexto in {"agregacao_top", "agregacao_bottom"}:
            mapa = {
                "padrao": [
                    "id_agrupado",
                    "descr_padrao",
                    "ids_origem_agrupamento",
                    "preco_medio_compra",
                    "preco_medio_venda",
                    "total_entradas",
                    "total_saidas",
                    "total_movimentacao",
                    "total_compras",
                    "qtd_compras_total",
                    "total_vendas",
                    "qtd_vendas_total",
                    "ncm_padrao",
                    "cest_padrao",
                    "gtin_padrao",
                    "lista_itens_agrupados",
                    "lista_ncm",
                    "lista_cest",
                    "lista_gtin",
                    "lista_descricoes",
                    "lista_desc_compl",
                    "co_sefin_padrao",
                    "co_sefin_agr",
                    "lista_unidades",
                    "fontes",
                ],
                "auditoria": [
                    "id_agrupado",
                    "descr_padrao",
                    "ids_origem_agrupamento",
                    "lista_itens_agrupados",
                    "ncm_padrao",
                    "cest_padrao",
                    "gtin_padrao",
                    "lista_ncm",
                    "lista_cest",
                    "lista_gtin",
                    "lista_descricoes",
                    "lista_desc_compl",
                    "co_sefin_padrao",
                    "co_sefin_agr",
                    "lista_co_sefin",
                    "co_sefin_divergentes",
                    "lista_unidades",
                    "fontes",
                    "total_entradas",
                    "total_saidas",
                    "total_movimentacao",
                    "total_compras",
                    "qtd_compras_total",
                    "preco_medio_compra",
                    "total_vendas",
                    "qtd_vendas_total",
                    "preco_medio_venda",
                    "lista_chave_produto",
                ],
                "estoque": [
                    "id_agrupado",
                    "descr_padrao",
                    "ids_origem_agrupamento",
                    "total_entradas",
                    "total_saidas",
                    "total_movimentacao",
                    "total_compras",
                    "qtd_compras_total",
                    "total_vendas",
                    "qtd_vendas_total",
                    "lista_unidades",
                    "lista_descricoes",
                    "lista_desc_compl",
                    "lista_itens_agrupados",
                    "fontes",
                    "ncm_padrao",
                    "cest_padrao",
                ],
                "custos": [
                    "id_agrupado",
                    "descr_padrao",
                    "ids_origem_agrupamento",
                    "preco_medio_compra",
                    "preco_medio_venda",
                    "total_entradas",
                    "total_saidas",
                    "total_movimentacao",
                    "total_compras",
                    "qtd_compras_total",
                    "total_vendas",
                    "qtd_vendas_total",
                    "lista_ncm",
                    "lista_cest",
                    "lista_gtin",
                    "lista_descricoes",
                    "lista_desc_compl",
                    "lista_itens_agrupados",
                    "lista_unidades",
                    "fontes",
                ],
            }
        elif nome in {"", "padrao"}:
            return colunas
        elif contexto == "conversao":
            mapa = {
                "auditoria": [
                    "id_agrupado",
                    "id_produtos",
                    "descr_padrao",
                    "lista_descricoes_produto",
                    "unid",
                    "unid_ref",
                    "fator",
                    "fator_calculado",
                    "preco_medio",
                    "preco_medio_ref",
                    "origem_preco",
                ],
                "estoque": [
                    "id_agrupado",
                    "descr_padrao",
                    "unid",
                    "unid_ref",
                    "fator",
                    "fator_calculado",
                ],
                "custos": [
                    "id_agrupado",
                    "descr_padrao",
                    "unid",
                    "unid_ref",
                    "preco_medio",
                    "preco_medio_ref",
                    "fator_calculado",
                    "fator",
                    "origem_preco",
                ],
            }
        elif contexto == "aba_mensal":
            mapa = {
                "exportar": [
                    "ano",
                    "mes",
                    "id_agregado",
                    "descr_padrao",
                    "ST",
                    "it_in_st",
                    "valor_entradas",
                    "qtd_entradas",
                    "pme_mes",
                    "valor_saidas",
                    "qtd_saidas",
                    "pms_mes",
                    "MVA",
                    "MVA_ajustado",
                    "entradas_desacob",
                    "ICMS_entr_desacob",
                    "saldo_mes",
                    "custo_medio_mes",
                    "valor_estoque",
                ],
                "auditoria": [
                    "ano",
                    "mes",
                    "id_agregado",
                    "descr_padrao",
                    "ST",
                    "it_in_st",
                    "valor_entradas",
                    "qtd_entradas",
                    "valor_saidas",
                    "qtd_saidas",
                    "entradas_desacob",
                    "ICMS_entr_desacob",
                    "saldo_mes",
                    "custo_medio_mes",
                    "valor_estoque",
                ],
                "estoque": [
                    "ano",
                    "mes",
                    "id_agregado",
                    "descr_padrao",
                    "unids_ref_mes",
                    "qtd_entradas",
                    "qtd_saidas",
                    "saldo_mes",
                    "custo_medio_mes",
                    "valor_estoque",
                ],
                "custos": [
                    "ano",
                    "mes",
                    "id_agregado",
                    "descr_padrao",
                    "valor_entradas",
                    "pme_mes",
                    "valor_saidas",
                    "pms_mes",
                    "custo_medio_mes",
                    "valor_estoque",
                ],
            }
        elif contexto == "aba_anual":
            mapa = {
                "exportar": [
                    "ano",
                    "id_agregado",
                    "descr_padrao",
                    "unid_ref",
                    "estoque_inicial",
                    "entradas",
                    "saidas",
                    "estoque_final",
                    "saidas_calculadas",
                    "saldo_final",
                    "entradas_desacob",
                    "saidas_desacob",
                    "estoque_final_desacob",
                    "pme",
                    "pms",
                    "ICMS_saidas_desac",
                    "ICMS_estoque_desac",
                ],
                "auditoria": [
                    "ano",
                    "id_agregado",
                    "descr_padrao",
                    "unid_ref",
                    "estoque_inicial",
                    "entradas",
                    "saidas",
                    "estoque_final",
                    "saldo_final",
                    "entradas_desacob",
                    "saidas_desacob",
                    "estoque_final_desacob",
                    "ICMS_saidas_desac",
                ],
                "estoque": [
                    "ano",
                    "id_agregado",
                    "descr_padrao",
                    "unid_ref",
                    "estoque_inicial",
                    "entradas",
                    "saidas",
                    "estoque_final",
                    "saldo_final",
                ],
                "custos": [
                    "ano",
                    "id_agregado",
                    "descr_padrao",
                    "unid_ref",
                    "entradas",
                    "saidas",
                    "pme",
                    "pms",
                    "ICMS_saidas_desac",
                ],
            }
        elif contexto == "nfe_entrada":
            mapa = {
                "auditoria": [
                    "data_classificacao",
                    "fonte_documento",
                    "tipo_operacao",
                    "nnf",
                    "prod_nitem",
                    "id_agrupado",
                    "descr_padrao",
                    "prod_xprod",
                    "prod_ncm",
                    "prod_cest",
                    "co_sefin_inferido",
                    "co_sefin_agr",
                    "it_pc_interna",
                    "it_in_st",
                    "it_in_isento_icms",
                    "it_in_reducao",
                    "it_pc_reducao",
                    "it_pc_mva",
                    "it_in_mva_ajustado",
                    "xnome_emit",
                    "xnome_dest",
                    "chave_acesso",
                ],
                "estoque": [
                    "data_classificacao",
                    "fonte_documento",
                    "id_agrupado",
                    "descr_padrao",
                    "prod_xprod",
                    "prod_ncm",
                    "prod_cest",
                    "co_sefin_agr",
                    "it_pc_interna",
                    "it_in_st",
                    "it_in_isento_icms",
                    "it_in_reducao",
                    "prod_ucom",
                    "prod_qcom",
                    "prod_vprod",
                ],
                "custos": [
                    "data_classificacao",
                    "fonte_documento",
                    "id_agrupado",
                    "descr_padrao",
                    "prod_xprod",
                    "co_sefin_agr",
                    "it_pc_interna",
                    "it_in_st",
                    "it_in_isento_icms",
                    "it_in_reducao",
                    "it_pc_reducao",
                    "it_pc_mva",
                    "it_in_mva_ajustado",
                    "prod_vuncom",
                    "prod_vprod",
                ],
            }
        elif contexto == "produtos_selecionados":
            mapa = {
                "auditoria": [
                    "id_agregado",
                    "descr_padrao",
                    "total_ICMS_entr_desacob",
                    "total_ICMS_saidas_desac",
                    "total_ICMS_estoque_desac",
                    "total_ICMS_total",
                ],
                "estoque": [
                    "id_agregado",
                    "descr_padrao",
                    "total_ICMS_entr_desacob",
                    "total_ICMS_estoque_desac",
                    "total_ICMS_total",
                ],
                "custos": [
                    "id_agregado",
                    "descr_padrao",
                    "total_ICMS_entr_desacob",
                    "total_ICMS_saidas_desac",
                    "total_ICMS_estoque_desac",
                    "total_ICMS_total",
                ],
            }
        elif contexto == "id_agrupados":
            mapa = {
                "auditoria": [
                    "id_agrupado",
                    "descr_padrao",
                    "lista_descricoes",
                    "lista_desc_compl",
                    "lista_codigos",
                    "lista_unidades",
                ],
                "estoque": [
                    "id_agrupado",
                    "descr_padrao",
                    "lista_unidades",
                    "lista_descricoes",
                    "lista_desc_compl",
                ],
                "custos": [
                    "id_agrupado",
                    "descr_padrao",
                    "lista_codigos",
                    "lista_unidades",
                ],
            }
        else:
            mapa = {
                "auditoria": [
                    "cnpj",
                    "periodo",
                    "id_agrupado",
                    "id_agregado",
                    "descr_padrao",
                    "descricao",
                    "descr",
                    "Descr_item",
                    "Ncm",
                    "ncm_padrao",
                    "cest_padrao",
                    "Cfop",
                    "valor_item",
                    "preco_item",
                    "q_conv",
                    "Qtd",
                    "total_compras",
                    "qtd_compras_total",
                    "preco_medio_compra",
                    "total_vendas",
                    "qtd_vendas_total",
                    "preco_medio_venda",
                    "saldo_final",
                    "entradas_desacob",
                ],
                "estoque": [
                    "id_agrupado",
                    "id_agregado",
                    "descr_padrao",
                    "descricao",
                    "Descr_item",
                    "ncm_padrao",
                    "Ncm",
                    "unid_ref",
                    "q_conv",
                    "Qtd",
                    "total_entradas",
                    "total_saidas",
                    "total_movimentacao",
                    "total_compras",
                    "total_vendas",
                    "saldo_final",
                    "estoque_final",
                ],
                "custos": [
                    "id_agrupado",
                    "id_agregado",
                    "descr_padrao",
                    "descricao",
                    "Descr_item",
                    "total_entradas",
                    "total_saidas",
                    "total_movimentacao",
                    "total_compras",
                    "qtd_compras_total",
                    "preco_medio_compra",
                    "total_vendas",
                    "qtd_vendas_total",
                    "preco_medio_venda",
                    "preco_item",
                    "preco_unit",
                    "valor_item",
                    "q_conv",
                    "Qtd",
                    "pme",
                    "pms",
                    "custo_medio_anual",
                ],
            }

        desejadas = mapa.get(nome, colunas)
        selecionadas = [c for c in desejadas if c in colunas]
        return selecionadas or colunas
    def _aplicar_layout_padrao_agregacao(
        self,
        contexto: str,
        table: QTableView,
        model: PolarsTableModel,
        perfil: str,
    ) -> None:
        if (
            contexto not in {"agregacao_top", "agregacao_bottom"}
            or model.dataframe.is_empty()
        ):
            return
        ordem = self._obter_colunas_preset_perfil(
            perfil, model.dataframe.columns, contexto
        )
        self._aplicar_ordem_colunas(table, ordem)
        colunas = model.dataframe.columns
        offset = 1 if getattr(model, "_checkable", False) else 0
        larguras = {
            "id_agrupado": 150,
            "descr_padrao": 320,
            "ids_origem_agrupamento": 180,
            "preco_medio_compra": 150,
            "preco_medio_venda": 150,
            "total_entradas": 145,
            "total_saidas": 145,
            "total_movimentacao": 155,
            "total_compras": 140,
            "qtd_compras_total": 140,
            "total_vendas": 140,
            "qtd_vendas_total": 140,
            "lista_ncm": 180,
            "lista_cest": 180,
            "lista_gtin": 180,
            "lista_descricoes": 340,
            "lista_desc_compl": 320,
            "lista_itens_agrupados": 340,
        }
        for nome, largura in larguras.items():
            if nome in colunas:
                table.setColumnWidth(colunas.index(nome) + offset, largura)
    def _aplicar_preset_mov_estoque(self) -> None:
        if self.mov_estoque_model.dataframe.is_empty():
            return
        visiveis = self._obter_colunas_preset_perfil(
            "exportar", self.mov_estoque_model.dataframe.columns, "mov_estoque"
        )
        self._aplicar_preset_colunas(
            self.mov_estoque_table, self.mov_estoque_model.dataframe.columns, visiveis
        )
        colunas = self.mov_estoque_model.dataframe.columns
        for nome, largura in {
            "descr_padrao": 320,
            "Descr_item": 320,
            "Tipo_operacao": 170,
            "id_agrupado": 140,
        }.items():
            if nome in colunas:
                self.mov_estoque_table.setColumnWidth(colunas.index(nome), largura)
    def _aplicar_preset_aba_anual(self) -> None:
        if self.aba_anual_model.dataframe.is_empty():
            return
        visiveis = self._obter_colunas_preset_perfil(
            "exportar", self.aba_anual_model.dataframe.columns, "aba_anual"
        )
        self._aplicar_preset_colunas(
            self.aba_anual_table, self.aba_anual_model.dataframe.columns, visiveis
        )
        colunas = self.aba_anual_model.dataframe.columns
        offset = 1 if getattr(self.aba_anual_model, "_checkable", False) else 0
        for nome, largura in {"descr_padrao": 320, "id_agregado": 140}.items():
            if nome in colunas:
                self.aba_anual_table.setColumnWidth(
                    colunas.index(nome) + offset, largura
                )
    def _aplicar_preset_aba_mensal(self) -> None:
        if self.aba_mensal_model.dataframe.is_empty():
            return
        visiveis = self._obter_colunas_preset_perfil(
            "exportar", self.aba_mensal_model.dataframe.columns, "aba_mensal"
        )
        self._aplicar_preset_colunas(
            self.aba_mensal_table, self.aba_mensal_model.dataframe.columns, visiveis
        )
        colunas = self.aba_mensal_model.dataframe.columns
        offset = 1 if getattr(self.aba_mensal_model, "_checkable", False) else 0
        for nome, largura in {
            "descr_padrao": 320,
            "id_agregado": 150,
            "unids_mes": 180,
            "unids_ref_mes": 180,
        }.items():
            if nome in colunas:
                self.aba_mensal_table.setColumnWidth(
                    colunas.index(nome) + offset, largura
                )
